sudo: required
langauge: python
python:
  - "2.7"
services:
  - docker
before_install:
- docker build . -t amara-uploader
- docker run -p 127.0.0.1:80:5000 amara-uploader
script:
  - docker ps | grep -q amara-uploader
